apiVersion: apps/v1
kind: Deployment
metadata:
  name: genkart-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: genkart-server
  template:
    metadata:
      labels:
        app: genkart-server
    spec:
      containers:
        - name: server
          image: {{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}
          imagePullPolicy: {{ .Values.image.server.pullPolicy }}
          ports:
            - containerPort: 5560
          envFrom:
            - secretRef:
                name: genkart-server-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: genkart-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5560"
spec:
  selector:
    app: genkart-server
  ports:
    - protocol: TCP
      port: 5560
      targetPort: 5560
  type: {{ .Values.service.server.type }}
