apiVersion: apps/v1
kind: Deployment
metadata:
  name: genkart-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genkart-client
  template:
    metadata:
      labels:
        app: genkart-client
    spec:
      containers:
        - name: client
          image: rajjaiswal23/gen-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          envFrom:
            - secretRef:
                name: genkart-client-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: genkart-client
spec:
  selector:
    app: genkart-client
  type: NodePort
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 30005
